### ISSUE TITLE
Handling PC Complaints 

### ISSUE THREAD

**Issue by roy-shchory** [TechnionYP5777/Smartcity-Smarthouse#114]
@yossigil brought up some issues regarding some words used in our project that may trigger the more sensitive population. I suggest the following mechanism:
- We will add a complaint button
- When the user presses the button a picture of my puppy zoey will appear
- They will relax and move on
There are no copyright issues, she is my puppy and objectively I believe she is the cutest thing ever.
-Here she is wearing a sweater:
![whatsapp image 2016-12-30 at 20 14 33](https://cloud.githubusercontent.com/assets/23057062/21596558/6e54ee4a-d145-11e6-83ae-5af9db55320b.jpeg)
-Here she is standing like a human!(so cute!):
![whatsapp image 2016-12-30 at 20 14 33 1](https://cloud.githubusercontent.com/assets/23057062/21596579/9bc7eb20-d145-11e6-9961-6305318f0d10.jpeg)
-Here are some pictures of here when she was just born:
![whatsapp image 2016-07-12 at 14 57 44](https://cloud.githubusercontent.com/assets/23057062/21596591/bfdb2392-d145-11e6-8ecd-5013d467a45b.jpeg)
![whatsapp image 2016-07-16 at 17 46 38](https://cloud.githubusercontent.com/assets/23057062/21596592/c2676f3a-d145-11e6-88eb-e57e7d964b3d.jpeg)
-I caught her!!!!:
![whatsapp image 2016-07-22 at 20 03 29](https://cloud.githubusercontent.com/assets/23057062/21596594/c52166fe-d145-11e6-9edf-5bb7ab2b73fc.jpeg)

**Comment by yossigil** [comment]
Lovely! Thanks for the good spirit @roy-shchory
