### ISSUE TITLE
Rename the project

### ISSUE THREAD

**Issue by yossigil** [TechnionYP5777/Smartcity-Smarthouse#125]
As per your decision. One of you should be admin.

**Comment by inbalzukerman** [comment]
@roy-shchory  @RonGatenio  @ylevv @EliaTraore @alexvitho 
Guys we really need to decide on this 😅 

At the moment the only idea I have is: " SmartCity-Sensors-Infrastructure "
Please comment on this option or suggest new ideas 😄

**Comment by inbalzukerman** [comment]
So, SmartCity-SmartHouse it is?
check if you agree -

- [ ] @RonGatenio  
- [ ] @roy-shchory 
- [ ] @alexvitho 
- [ ] @EliaTraore 
- [ ] @ylevv

**Comment by EliaTraore** [comment]
Well we've decided.  @yossigil  can you change it/ make me admin so I'll do it?

**Comment by EliaTraore** [comment]
nvm, done :)
