### ISSUE TITLE
Allowing apps to operate sensors

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#130]
In order to allow applications to influence the state of the smart-house the functionality of the sensors and the applications need to be extended. This will require:
- [x] Extending the application API provided by the system to allow applications to send instructions to sensors (the format of the instructions is agreed externally between the application and sensor developers). This will result in extending the system itself to forward the actual instructions.
- [x] Extending the sensors class to have a bidirectional connection with the system to allow incoming instructions.

Sub-issues will be opened after additional reviewing of the current sensors and application classes

Working - time estimation: 2-3 days total.

**Comment by ylevv** [comment]
The functionality was added but we still need to do test it, so this issue remains open.

**Comment by EliaTraore** [comment]
As requested by Tanya in today's meeting, This issue will be closed and another one regarding the testing of this feature will be opened
