### ISSUE TITLE
Logging Managment

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#135]
Research upon a logging system for our project.
As discussed in our meeting, try to research first the classes `Fault` and `Monitor` from the Spartanizer project.

**Comment by RonGatenio** [comment]
started working on a wiki page for [Log4j](../wiki/Logging-with-Log4j)

**Comment by inbalzukerman** [comment]
@RonGatenio, can this issue be closed?

**Comment by RonGatenio** [comment]
not yet... I need read about slf4j first
@inbalzukerman

**Comment by inbalzukerman** [comment]
Let us know so we could start working on #146, #147, #148 😄

**Comment by RonGatenio** [comment]
@inbalzukerman 
You can start working on those issues.
If we will change from Log4j to Slf4j, the changes to the code will be minor, because their syntax is identical.

**Comment by inbalzukerman** [comment]
Yay! Thank you 👍

**Comment by RonGatenio** [comment]
I changed the logger to slf4j (I'll explain why later). For now, this is the new syntax:
```java
import org.slf4j.LoggerFactory;
import org.slf4j.Logger;

public class MyClass {
    private static Logger log = LoggerFactory.getLogger(MyClass.class);
}
```

**Note** that log4j is still accessible (slf4j uses log4j... again, I'll explain this later...). **So avoid using it!**

Also, there is no longer a `fatal` alert level 😢 
<hr>
The old syntax (for a remainder):

```java
import org.apache.log4j.Logger;

public class MyClass {
    private static Logger log = Logger.getLogger(MyClass.class);
}
```

**Comment by RonGatenio** [comment]
Something nice about the logger...
You can log a string and an exception in the following way:
```java
public void myFunc() {
   try {
      //...
   } catch (Exception e) {
      log.error("Big error, very bad!", e);
   }
}
```
This will log the string and the stack trace:
```
2017-04-08 03:40:02 ERROR [JavaFX Application Thread] api.SmartHouseApplication (SmartHouseApplication.java:54) - Big error, very bad! 
java.lang.IllegalStateException: Location is not set.
	at javafx.fxml.FXMLLoader.loadImpl(FXMLLoader.java:2434)
	//...
	at java.lang.Thread.run(Unknown Source)
```

#146 #147 #148

**Comment by RonGatenio** [comment]
Another thing, try to avoid `System.out.println("...")` in the code... 
Use `log.debug("...")` instead
