### ISSUE TITLE
Persistent System

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#136]
Research which way is the best to make our system  persistent.
Since working with the Parse server is a big help in this issue, we will try to combine moving our DB to Parse  and making our system persistent.

**Comment by yossigil** [comment]
:+1:

**Comment by RonGatenio** [comment]
This is issue is been put on hold because we chose to do all of the persistent functionality on the server... so we need to wait for the server.

**Comment by RonGatenio** [comment]
The FileSystem (#175) and the DatabaseManager handle the persistency issue.

@inbalzukerman can we close this?

**Comment by inbalzukerman** [comment]
Yay 😄  Sure
