### ISSUE TITLE
Reorganize the project's structure in maven modules

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/Smartcity-Smarthouse#139]
In order to make our API easier to distribute, we should place it in a separate project (or maven module) that can be compiled on its own. In addition, the application should also be placed in a separate project, for similar reasons.

My idea is to reorganize the project into the following maven modules:
- CommonToolkit (for common utils, and log4j2.xml)
- SmarthouseSystem
- SmarthouseAPI
- SosApplication
- SosSensor
- StoveApplication
- StoveSensor
- VitalsApplication
- VitalsSensor

The idea was taken from the SmartCity-Market project: [SmartCity-Market - Project Directory Layout and high level design](https://github.com/TechnionYP5777/SmartCity-Market/wiki/Project-Directory-Layout-and-high-level-design)

**Comment by RonGatenio** [comment]
After researching, I discovered a problem with this idea:

Usually, when dividing a project into modules, there should be at least one module for integration tests. This module will have dependencies for the other modules, and will have only tests (`testModule` in the following example):
```
multi-module-failing-example
|-- pom.xml
|-- product
|   |-- pom.xml
|   `-- src
|       `-- main
|           `-- java
|               `-- se
|                   `-- sigma
|                       `-- calculator
|                           `-- Calculator.java
`-- testModule
    |-- pom.xml
    `-- src
        `-- test
            `-- java
                `-- se
                    `-- sigma
                        `-- calculator
                            `-- CalculatorTest.java
```

The problem is that code coverage by `Cobertura` (which must be used for codecov.io support) don't consider integration tests in the coverage, as explained here:
[Test coverage in a multi module Maven project](http://www.thinkcode.se/blog/2012/02/18/test-coverage-in-a-multi-module-maven-project).
This post also proposes a solution, but it is hard to integrate it with `Travis`...

I'll keep searching for a solution...

**Comment by RonGatenio** [comment]
For now, everybody can continue their work on the project... 
@roy-shchory @inbalzukerman @EliaTraore @ylevv @alexvitho

**Comment by EliaTraore** [comment]
Don't forget to write an "install me" wiki after this issue is done :smile:

**Comment by RonGatenio** [comment]
Here is a side project I made, in order to find a solution for the integration tests coverage problem:
https://github.com/RonGatenio/SmarthouseTemp

**Comment by RonGatenio** [comment]
This took longer than expected, but it works now!
I found a solution to the problem, and I'll write a wiki about it.

for now, you can look at this [commit](https://github.com/RonGatenio/SmarthouseTemp/commit/a1058c74cf4892e3a94b9c6fd60af6bb98607747) from my test project.

and this is the coverage from [codecov](https://codecov.io/gh/RonGatenio/SmarthouseTemp/commit/a1058c74cf4892e3a94b9c6fd60af6bb98607747)

**Comment by RonGatenio** [comment]
Now that the codecov problem is resolved, we can start restructuring the project. But I don’t want to do this alone… 
We need to decide on the new structure together, and we will do so after the vacation.
