### ISSUE TITLE
Sensors' server on deadlock

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#143]
Currently, our server works like this - 
```java
final Socket client = server.accept();
//omitted- code responsible for starting a thread responsible for the accepted connection
final Socket sensor = router.accept();
//omitted- code responsible for starting a thread responsible for the accepted connection
```
Which creates a bug in 2 ways:
- `accept` is a blocking method. A regular sensor will not try to connect on port 40,002 (the instruction port) and so the server will wait on 40,002 forever
- In the `InteractiveSensor` there's the method `registerInstructions` which tries to connect to the server on the instruction port. This means that in order to fully connect you have to write the following code: 
```java
s.register();
s.registerInstructions();
```
you can easily forget to call the second method, resulting again in the server waiting on 40,002 indefinitely.

**Comment by EliaTraore** [comment]
The best solution imo - 
- in `Sensor` class - add a protected field called sType  (which could be an enum) with a default type of `NON_INTERACTIVE`.
- in `InteractiveSensor` class -
    - the c'tor will set the sType to `INTERACTIVE`,
    - the  register method will override the original method and initiate the second connection after the super is done
- in `RegisterMessage` class -  the c'tor will receive that type and add that information to the sent message.
- in `SensorsHandler` class - listening on 40,002 will depend on the type in the `RegisterMessage`

**Comment by ylevv** [comment]
@EliaTraore 
Overriding `register()` "forces" both connection to succeed at once. In case the first connection succeeds but the second connection fails, the GUI developers (that must call `register()`) should retry only the second connection, but they won't know it...

**Comment by ylevv** [comment]
@EliaTraore agreed to cancel the overriding, thus this issue can be closed 😄
