### ISSUE TITLE
Extending the system's server 

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#149]
At the moment, the system keeps a list of listeners for each sensor and use them to notify subscribed applications when the sensors send new data. This solution will not be viable after the migration to the cloud is completed.
Therefore there's a need to decide on the new method of receiving the data. Current options are:
- the system will poll the cloud for new data
- the server's logic will be transformed to the cloud.
The second solution, while being the non-trivial one, is preferred since polling is less logical and slower. However, there might be a need to learn to much in order to implement cloud server. 

As a result this issue will be conducted as follows:
 -  Research servers on cloud. Especially:
    - using our current data cloud for server purposes
    - using [Atmosphere Framework](https://github.com/Atmosphere/) @roy-shchory  found
 - Implement the chosen method

Working time estimation - 
- research - 4 days (not flexible - this should be enough to determine the complexity of the 2nd solution)
- implementation - TBD (depends on research results)

**Comment by EliaTraore** [comment]
Since the project is still in the process of updating the DB and this wasn't in the original Ducking milestone goals, we can postpone this issue to the next milestone without hurting the current performance.

**Comment by inbalzukerman** [comment]
@EliaTraore  can be closed? Haven't we decided not to migrate the sensors' server to the cloud?
