### ISSUE TITLE
Change sensors messaging interface

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/Smartcity-Smarthouse#162]
The developer shouldn't use individual sensors, but instead he should be able to listen to certain messages that will flow through the system.

This interface will be similar to a registry. All sensor will write information to the registry, and the applications will be able to listen for entries in the registry.

We are still not sure how to this...
We will need to open more issues about this big architectural change.

**Comment by inbalzukerman** [comment]
More information about the new feature will be found in: [https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/First-Client-Meeting](url)

Some research regarding the changes required in the database management will be found in: #159

**Comment by RonGatenio** [comment]
Finished the new SensorApi (#176) and the new FileSystemService (#177).
Both work with the new FileSystem (#175)

- The client can use the FileSystemService  to listen on any path.
- To work with sensors, it is still easier to use a SensorApi. The old one was problematic, but the new one is great and easy to use.
