### ISSUE TITLE
Research libraries of dashboard management

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#164]
After today's meeting with Yossi, we decided to add a feature of a dashboard to our project. Information and explanations can be found in the relevant  wiki page 😄 

Before we head to the implementation part, we need to decide on a convenient library to work with.

This issue will be closed after information about existing libraries will be collected.

**Comment by inbalzukerman** [comment]
@ylevv you can close this issue thanks to your great work 😄

**Comment by ylevv** [comment]
This is the chosen library: https://github.com/HanSolo/tilesfx
A demo can be found here: https://github.com/HanSolo/tilesfxdemo
