### ISSUE TITLE
Ideas of sensors

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#165]
Since we will be working on the dashboard soon, we need to think about at least 20 sensors ideas!

If to be more exact - the dashboard will present the streams of information received from across the smart-house, and we are responsible to demonstrate it. Since we are working with sensors' simulations,  we can and should be creative. 

This issue will be closed after at least 20 sensors ideas will be decided upon.

**Comment by roy-shchory** [comment]
### **billing streams  -** 
- electricity,water,phone consumption streams
### **toilet streams -** 
- shower stream (how long is he in the shower)
- toilet streams (usage - how often and how long combines butt sensor pee sensor and flush sensor)
- cabinet stream(how often does he access his grooming products/medication)
### **kitchen stream  -** 
- stove and oven streams (temperature and working duration) 
- fridge stream(how often does the door get opened, temperature - so we know it works properly) 
- sink stream(how often does he use the sink and for how long. accumulation of dirty dishes)
- coffee maker stream(how many cups a day)
### **living room streams  -** 
- seating stream (how long is he sitting on each couch/seat can create a pie chart)
- tv stream(how much time is the tv on - could also stream the channel he is watching)
### **bedroom streams  -** 
- bed stream(how much time is he spending in bed)
### **General streams  -**
- house temperature stream
- blinds stream (are they open or close) 

@yossigil

**Comment by alexvitho** [comment]
### movement sensor - show the activity in each area.
### noise sensor - shows noise levels in each area.
### enterance camera (sensor) - transmits video stream of enterance.
### child monitor sensor - breathing , activity e.t.c. 
### cooking gas levels sensor (and alarms)
### humadity lelvel in each area.
### laundry level (weight , quantity)
### Smart postbox (number of incoming letters , real time allerts e.t.c.)
### Pill dispenser - number of pills, times, e.t.c.
### irrigation controller ( shows humidty, and have the option to make actions).
### pets food sensors.

**Comment by inbalzukerman** [comment]
This issue is completed and the ideas which were suggested will be taking into consideration 😄
