### ISSUE TITLE
Research on Ping protocol implementation

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#167]
The new dashboard feature will present streams of information received from the different  sensor in the house. One of the required functionalities by the client, is a "liveliness" status of the sensors.

The recommended way to achieve this option is to implement our simple "ping" protocol which will allow our system to send messages to the sensors once in a while and receive a response to confirm "liveliness".

This issue will be closed after some research upon a simple ping protocol implementation options will be conducted.

**Comment by EliaTraore** [comment]
Since we have 1 month till the end of our project, and more specific feature requests derived from the client focus group meeting, we have decided to re-priorites this issue as NTH.

**Comment by inbalzukerman** [comment]
Since this issue is defined NTH, and this is the presentation day, this issue will not be pursued.
