### ISSUE TITLE
Research upon Event Systems

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#168]
since we are bound  to change the messaging architecture and use a hierarchical message structure, some research should be done on standard fields we would like to use.

Yossi suggested we will read some of Opher Etzion's work on the topic.

This issue will be closed when a set of standard useful fields will be decided upon.

**Comment by RonGatenio** [comment]
I have an idea for the implementation of an event system:
The idea is that our system will have a single EventDispatcher object that will dispatch incoming messages.
The EventDispatcher will work with the following types of message paths:
`A.B.C` => complete path
`A.B.*` => incomplete path, listening for children
`A.**` => incomplete path, listening for sub-tree

The EventDispatcher will accept messages with a complete path, and accept listeners with a complete or incomplete path.

The EventDispatcher will define an internal listeners tree, and call the listeners after receiving a message with a matching path.

Uses:
1. The sensors could send messages to the dispatcher, and the databaseHandler will listen to all types of message from the dispatcher.
2. The applications could listen to message from the dispatcher.
3. All system components will communicate via the dispatcher. For example, if one of the cores wants to save all of the system’s data, it could send a message on the path: `system.internals.saveme`, and an eventHandler will save the system

**Comment by inbalzukerman** [comment]
The purpose of this issue is not to design an event system, but to earn from existing event system on useful\ common standard field from which the messages in our system will be composed. 

At the moment, our `System` module as a whole is somewhat the "dispatcher" of the communication in the project. I understand you have some new design ideas here which you are testing on the co-responding branch,  therefore I will soon update this issue's description.

In addition, please notice that part of your implementation idea's functionalities have been already implemented by me. I think we should discuss our further work on this matter to make sure it all goes well 😅

**Comment by RonGatenio** [comment]
I think we understand the idea of an event system.
Closing this
