### ISSUE TITLE
Change applications' updates

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#172]
Since the messaging mechanism is being changed (#169), some modifications are bound to be made in the applications' management and the data dispatcher part of our system.

This issue will be closed when:

- [x] The relevant changes in `DatabaseHandler` will be implemented
- [x] Necessary query methods will be implemented (for notifying the application)
- [x]  Receiving and sending the messages to the applications by the system will be changed

**Comment by EliaTraore** [comment]
If I'm not mistaken, the system-apps communication have been updated. Am I missing something or can this issue be closed?
