### ISSUE TITLE
Update the sensors' side to use the event system

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#179]
The architectonic changes of the project with regrads to the event system and the new structure of messages require some adjustments on the sensors side.
This issue will be closed after those adjustments are completed

**Comment by inbalzukerman** [comment]
Please pay attention - As you may see, issue #169  have adjusting the sensors side to the new changes all covered... The change in this matter you took on yourself is sending the `done` message. No further changes are required as far as I know 😄

**Comment by EliaTraore** [comment]
This issue description isn't accurate enough, but this isn't a duplicate of #169 since its implementation went beyond the scope of that issue, as can be seen from the referenced commits.
This issue have however accomplished it goal (full integration and data-flow. YAY) so it can be closed.
