### ISSUE TITLE
Write the Backend of the Sensors Simulator

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#182]
~Any following feature development of the GUI side of the sensor simulator (ss) can be referenced to here.~ Gui development  (and integration ) in #198 , backend here

This issue will be closed after we the sss is fully functional from code, meaning -  
- [x] sensors defined through the simulator will be:
    - [x] created and registered to the system
    - [x] sending regular updates based on their creation arguments
- [x] the simulated sensors will be bi-directional (instructions will be consumed by a consumer given from the sss)

**Comment by inbalzukerman** [comment]
Let's not use ss as an acronym 😓  It have been used before and not for good purposes..

**Comment by EliaTraore** [comment]
> [Trump is elected the pc age is gone.](https://github.com/TechnionYP5777/Smartcity-Smarthouse/issues/105#issuecomment-269789695)

But we can use SsS (**S**ensor**s** **S**imulator) if its that important
