### ISSUE TITLE
Implement missing GUI tests

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#183]
As can be seen in the commits referencing #131, only the vitals and stove GUIs have been tested.
This issue will be closed when the remaining GUI is tested:
- [ ] System
- [ ] SOS application and sensor
- [ ] Shutter application and sensor

**Comment by inbalzukerman** [comment]
Since this issue is defined NTH, and this is the presentation day, this issue will not be pursued.
