### ISSUE TITLE
Support user mode and developer mode

### ISSUE THREAD

**Issue by ylevv** [TechnionYP5777/Smartcity-Smarthouse#189]
As agreed, we will create two modes of the Smart-House: user mode and developer mode.
This change includes several steps:
- [x] Add a pop up message in which the user will choose the desired mode.
- [x] Display relevant description, based on the chosen mode
- [x] Change theme based on the chosen mode (light theme - user; dark theme - developer)
- [x] Display only relevant tabs, based on the chosen mode

**Comment by RonGatenio** [comment]
`il.ac.technion.cs.smarthouse.system.gui.main_system.MainSystemGuiController#initialize`:
```java
@Override
    protected <T extends GuiController<SystemCore, SystemMode>> void initialize(SystemCore model, T parent,
                    SystemMode m, URL location, ResourceBundle b) {
...
}
```

As you can see, the `SystemMode` is passed down into each `SystemGuiController`

**Comment by ylevv** [comment]
I also should
- [ ] Hide the plus button and Drag&Drop area from the applications tab in Developer Mode.

**Comment by ylevv** [comment]
After discussing the themes issue with @RonGatenio, we decided that using a CSS file is the best method to change the style of the screens in Developer Mode, as it will make future style modifications easy to apply.
