### ISSUE TITLE
General error handling

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/Smartcity-Smarthouse#190]
We need to notify the user in cases of an unexpected error

**Comment by RonGatenio** [comment]
![err](https://user-images.githubusercontent.com/15971916/27113209-45c374e8-50c4-11e7-9e53-6396976b132a.gif)

**Comment by RonGatenio** [comment]
@EliaTraore @inbalzukerman @ylevv @roy-shchory 
If someone wants to edit the alert box, look for it in the `SystemPresenter`

We should add a send report...

**Comment by RonGatenio** [comment]
@ylevv 
I moved this alert into [system.SystemFailureDetector.java](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/d19ee231119348adb0b457a4aed2ea53430f4174/System/src/main/java/il/ac/technion/cs/smarthouse/system/SystemFailureDetector.java)

**Comment by ylevv** [comment]
An option to send report was added so this issue can be closed 😄
