### ISSUE TITLE
Reorganize the user information tab

### ISSUE THREAD

**Issue by ylevv** [TechnionYP5777/Smartcity-Smarthouse#192]
Instead of having sub-tabs of "user information" and "emergency contacts" inside the user information tab, we decided to merge them into one `SplitPane` window.

**Comment by EliaTraore** [comment]
There we're 2 problems regarding the user information tab - 
- Uninformative error messages - It's hard to understand why the input is wrong (possible: the input doesn't allow spaces in the name text field)
- No indication of successful registration

Can those problems be fixed under this issue?

**Comment by ylevv** [comment]
Sure 👍
