### ISSUE TITLE
Add GUI hints to the system

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#194]
Scan the system (and simulator) GUI for places were explanation is needed, and add a `Tooltip` with the explanation.
Optional: create a util custom tooltip class that allows
- Customizing the delay and duration of the hint presentation.
- Set the hint to disappear on click (instead of after time) ?

This issue will be closed when the GUI is sufficiently covered with hints.

**Comment by ylevv** [comment]
Hints and / or `Tooltip`s should be added in:
- Applications tab:
    - [ ] Applications list
    - [ ] Application section
    - [ ] Installer section
- Sensors tab:
    - [ ] Mapping section
    - [ ] Sensors
- User information tab:
    - [ ] User information section
    - [ ] Emergency contacts section
- Dashboard:
    - [ ] Plus button
    - Configuration:
        - [ ] Add path button
        - [ ] Remove path button
- [ ] Sensors' Simulator
