### ISSUE TITLE
Develop the widget region

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#196]
Implement `class WidgetsRegionBuilder`.
This issue will be closed when:
- [ ] Widgets can be added to the widget region through the API.
- [ ] The widgets are updated to show the received information on the listen paths.
- [ ] There is a way to add the widgets in the region to the system dahsboard.

**Comment by RonGatenio** [comment]
Looks amazing @EliaTraore! Great job 👍 😄 
I made some gifs so everybody can see this

### The widgets
![stove1](https://user-images.githubusercontent.com/15971916/27251988-af5a5432-535b-11e7-879f-769d1ffbee99.gif)

### Add to home screen
![stove2](https://user-images.githubusercontent.com/15971916/27251998-dab433d2-535b-11e7-81ec-f4c6440e36a3.gif)
