### ISSUE TITLE
Update the simulator GUI

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#198]
The GUI will contain 3 views - 
- Sensors view: Shows the sensors in the same way as the mapping GUI does, and have add and config buttons.
- Add sensor view: allows setting the commercial name, alias, location, information sending paths & types, is bi-directional, instructions paths (only if bi-directional)
- Config messages view: allows sending a single message and stream of messages. 
         In stream of messages - `Number` are given by range, `Boolean` by checkboxs ticked for legal boolean values, `String` by a list defined in free text.

This issue will be closed when the following is achieved:
- [ ] The GUI views are implemented
- [ ] The simulator allows initializing the simulator with code-defined sensors
- [ ] The simulator is in a separate module ( **omg its a different jar!** ). That module will have a dependency to the `Common` module (and the `System` module will have a dependency to the simulator module)

**Comment by RonGatenio** [comment]
Make sure that the controller for this GUI is inhering from [`GuiController` (from Common)](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/Common/src/main/java/il/ac/technion/cs/smarthouse/gui_controller/GuiController.java)
