### ISSUE TITLE
Rename packages and classes

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#199]
See title.

**Comment by RonGatenio** [comment]
Don't know how, but someone has to rename **everything** in the [`SystemPresenterFactory`](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/System/src/main/java/il/ac/technion/cs/smarthouse/system_presenter/SystemPresenterFactory.java)

**Comment by inbalzukerman** [comment]
It has been decided, by some members of the group, not to rename the packages and classes in the project. Therefore, this issue should be closed.
