### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#202]
Review the code, fix when possible, blame where not.
TBD: code review guidelines

**Comment by RonGatenio** [comment]
About `log.error`:
- sometimes we should throw a `RuntimeException` after them (if we know that recovery is hard)
- but sometimes it is ok to continue without another throw

We should go over all of the `log.error`s and check

**Comment by EliaTraore** [comment]
[This wiki](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/Week-10) contains the list of specific rules agreed upon in the team meeting.

**Comment by RonGatenio** [comment]
Guidelines:
- [wiki/Week-10#coding-standards](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/Week-10#coding-standards)
- [wiki/Coding-Standard](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/Coding-Standard)

**Comment by ylevv** [comment]
Code review progress:
- [ ] Applications
- [ ] Sensors Simulator
- [ ] Common
- [ ] System:
    - [ ] developers API
    - [ ] GUI
    - [ ] notification center
    - [ ] system
    - [ ] system presenter
    - [ ] Entry
- [ ] Tests
