### ISSUE TITLE
Add "Try to Recover" button at the error reporting window

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#206]
see title. ask @RonGatenio for details

**Comment by RonGatenio** [comment]
look in [SystemFailureDetector.java](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/System/src/main/java/il/ac/technion/cs/smarthouse/system/SystemFailureDetector.java).

- Add the `Try to recover` button to the alert ([line 44](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/System/src/main/java/il/ac/technion/cs/smarthouse/system/SystemFailureDetector.java#L44)).
- Make sure that when clicked, `System.exit(-1);` [(line 81)](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/System/src/main/java/il/ac/technion/cs/smarthouse/system/SystemFailureDetector.java#L81) is not called. This will create a "try to recover" effect.

**Comment by RonGatenio** [comment]
`system.SystemFailureDetector.java` moved to [`system.failure_detector.SystemFailureDetector.java`](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/System/src/main/java/il/ac/technion/cs/smarthouse/system/failure_detector/SystemFailureDetector.java)

**Comment by EliaTraore** [comment]
additionally,  if you have a nested exception - do not try to recover and just exit

**Comment by inbalzukerman** [comment]
Added the required functionality and enlarged the Alert to make it possible to see  the error description and all the buttons 😄
