### ISSUE TITLE
Extend our widget selection

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#214]
Since the widgets help the user/developer to present important information in an easy to read manner, its important to have wide selection of available widgets.
This issue will be closed when our collection is sufficiently bigger.
Optional widgets:
- [x] Another graph widget, preferably a one that does not accumulate information, since its the suspected reason for the heisenbug at #211 
- [x] Widgets that represent information in string and boolean form well, since those are part lf the expected types of data received from the sensors

Optional features:
- [ ] Add a description to each widget, and update the config window GUI accordingly to present that description to the user (this could brance out to a new issue)

**Comment by EliaTraore** [comment]
A good place to start - `switchTile` in hansolo demo. It could make a decent boolean widget representation, if you could change its text somehow to correspond to the value (t/f) as well. If you choose to add this widget, notice that there's no need to set the `onSwitch[Un]Pressed` properties, and instead call `tile.fireEvent(<event>).`
Another good place would be the `CustomTile` which can be loaded with any javafx element, in case you need a lot of design freedom.

**Comment by EliaTraore** [comment]
Alternatively to the 1st optional widget, you could change the `LINE_GRAPH` to work with threads safe consumer-producer queue. I believe that an implementation exists within the java API, but if not there must be something freely available online.

**Comment by inbalzukerman** [comment]
As @EliaTraore suggested, adding the description for each widget is now branched out to another issue. See #220.
