### ISSUE TITLE
GuiBinderObject Bug?

### ISSUE THREAD

**Issue by ylevv** [TechnionYP5777/Smartcity-Smarthouse#215]
This is from the stove app. I changed both time and temperature thresholds with mouse + keyboard and not with the up / down arrows.

![bug](https://user-images.githubusercontent.com/22223943/27385681-254f3a70-569c-11e7-97bd-f35a87cfe590.PNG)

You can see that both time and temperature current values are higher than their thresholds, yet the numbers in the status section are not red.

@RonGatenio is it possible the bug is in GuiBinderObject?

**Comment by RonGatenio** [comment]
About the temperature (it is misspelled in the app 😁):
Try to play with the sensors temperature bar...
If you change this param in the app, and there isn't any new message from the sensor, the color won't update
(I will fix this later...)

About the time... I have no idea... maybe you didn't press ENTER, so the value didn't really change.
If that is the case, I will add an indicator that the value use changed (like in the text field of the configuration region)

**Comment by ylevv** [comment]
> maybe you didn't press ENTER, so the value didn't really change.

That's indeed the case for both fields... 😅
Maybe an "Update" button will be more intuitive (I had no idea ENTER would do the update).

**Comment by EliaTraore** [comment]
Maybe a "saved" label showing for few seconds after the value have been save will be enough of an indication?

**Comment by ylevv** [comment]
But then if the user don't know it should appear, he / she might think the value was updated while it did not.

**Comment by RonGatenio** [comment]
I will make the spinner like the text field:
![text](https://user-images.githubusercontent.com/15971916/27387100-70a08a70-56a0-11e7-8bae-4c5b3f69789c.gif)

Both ENTER and OK will work

**Comment by RonGatenio** [comment]
Can someone please fix the misspelled "tempeture" to "temperature"? 😁

**Comment by ylevv** [comment]
Looks great!
I can do it 😁
