### ISSUE TITLE
Make the spinner fields more intuitive in the configuration region

### ISSUE THREAD

**Issue by RonGatenio** [TechnionYP5777/Smartcity-Smarthouse#216]
look in #215 for the explanation

**Comment by inbalzukerman** [comment]
Since @ylevv is already on the fly with making GUI more intuitive, maybe she can take this under control?
@ylevv what do you say?

**Comment by RonGatenio** [comment]
Good idea
Try to look in [gui.javafx_elements.AppTextField.java](https://github.com/TechnionYP5777/Smartcity-Smarthouse/blob/master/System/src/main/java/il/ac/technion/cs/smarthouse/gui/javafx_elements/AppTextField.java) for help

**Comment by ylevv** [comment]
Sure 😄
