### ISSUE TITLE
Final - Wiki access

### ISSUE THREAD

**Issue by inbalzukerman** [TechnionYP5777/Smartcity-Smarthouse#232]
Anyone who needs access / a wiki page for his report - please comment on this issue 😄

**Comment by AnnaBel7** [comment]
🙋🏻

**Comment by inbalzukerman** [comment]
@AnnaBel7 just added you as collaborator to the project, you may add a wiki for yourself 😊

**Comment by inbalzukerman** [comment]
@rodedzats @kobybs @NetanelFelcher @DavidCohen55 @dshames - I added you as collaborators as well, you may open as many wikis as you'd like 🎉 😄
