### ISSUE TITLE
Bug in adding new emergency contact

### ISSUE THREAD

**Issue by NetanelFelcher** [TechnionYP5777/Smartcity-Smarthouse#234]
![image](https://user-images.githubusercontent.com/23153327/27768970-b7f1fad6-5f28-11e7-9f9a-511b859cedeb.png)
I tried to add a new emergency contact. 
All the tabs were green but there was a null pointer exception

**Comment by inbalzukerman** [comment]
Hi :)  We are working on it ⛑

**Comment by DavidCohen55** [comment]
I've encountered with this to...

**Comment by EliaTraore** [comment]
**Suspected cause**: persistence requires saving files into the filesystem, which is more problematic from jar (we didn't take care of that because we are usually working on the source code)
**Temporary workaround**: clone the repo and run the house through eclipse

**Comment by ylevv** [comment]
Fixed the bug, now if you don't select an emergency level (although you should), a proper popup appears.
We will release later.
Workaround: if you want the updated version, please clone the project.
