### ISSUE TITLE
App crashes when saving empty contact member

### ISSUE THREAD

**Issue by dshames** [TechnionYP5777/Smartcity-Smarthouse#235]
Hey, I added one contact to my user. Then I tried to add an empty one and got an exception:

[![EXCEPTION.jpg](https://s9.postimg.org/romyt3v2n/EXCEPTION.jpg)](https://postimg.org/image/627yc2wi3/)

**Comment by inbalzukerman** [comment]
Hi :) We are working on it ⛑

**Comment by dshames** [comment]
After this bug, I opened the app again,  and I couldn't see Ofri, the contact I added before the crash.

**Comment by inbalzukerman** [comment]
Thank you for the last note, we will check it as well

**Comment by roy-shchory** [comment]
did your personal information load or did it load empty?

**Comment by dshames** [comment]
It loaded. (not empty)

**Comment by roy-shchory** [comment]
because the app crashed it did not save.
you should use the try to recover button instead of the close button when errors happen.

**Comment by inbalzukerman** [comment]
This bug was fixed in #234 😄
