### ISSUE TITLE
App allows to add same contact twice

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#236]
I've tried to add the same contact twice as emergency contact and its works, should it?
please ignore the red fields down...

![image](https://user-images.githubusercontent.com/23057199/27769050-fcf9c41e-5f29-11e7-992d-2b45a3d44cc0.png)

**Comment by EliaTraore** [comment]
Severity: Slight
Status: **not being debugged**
Reason: As part of the design we trust the user to add contants smartly. You can even add yourself if you would like to receive notification on changes in you house.
