### ISSUE TITLE
App crashes when adding a widget

### ISSUE THREAD

**Issue by dshames** [TechnionYP5777/Smartcity-Smarthouse#238]
When trying to add a blank widget, the app crashes:

[![EX1.jpg](https://s24.postimg.org/856dwnyqd/EX1.jpg)](https://postimg.org/image/bosbmh1g1/)

**Comment by EliaTraore** [comment]
Can you please describe the steps you took that cause the problem? specifically:
- which widget did you try to add
- what was the source of information to the widgets (which paths?)

**Comment by dshames** [comment]
[![Ex2.jpg](https://s1.postimg.org/6vs7hl4y7/Ex2.jpg)](https://postimg.org/image/6j0tbemob/)

pressed on ok

**Comment by inbalzukerman** [comment]
This error occurred since you tried to add a widget without choosing a data path nor widget type. Similar error was described in #240 

We are aware to this problem, and will pay attention to it.

A workaround- try to add all needed configuration details 😄

**Comment by inbalzukerman** [comment]
Thank you for your review, the bug you described has been fixed 👍
