### ISSUE TITLE
Adding to dashboard crashes

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#240]
When I've tried to add to this screen I've got an error

![image](https://user-images.githubusercontent.com/23057199/27769134-e0845d10-5f2b-11e7-990e-aa799f547800.png)
![image](https://user-images.githubusercontent.com/23057199/27769136-ea5adb84-5f2b-11e7-8ede-dd48f1ffb04f.png)

**Comment by inbalzukerman** [comment]
@DavidCohen55 did you add a data-path to listen to?

**Comment by DavidCohen55** [comment]
How can I do it?

**Comment by inbalzukerman** [comment]
By opening the `<choose path>` combobox. Please pay attention there should be sensors connected to the system before 😄

**Comment by DavidCohen55** [comment]
OK, there isn't any sensors on my system, I will try now to work with your new jar and then comeback
also isn't not choosing a path leads to a crash should be a bug?

**Comment by inbalzukerman** [comment]
It is, of course, I'm trying to help you find a workaround.

**Comment by DavidCohen55** [comment]
I've successfully added a widget 🎊 
But I've found another error, if after you choose Widget Type, but don't press on any of them but fill the other fields the app shows NullPointerException

**Comment by inbalzukerman** [comment]
@DavidCohen55  you are describing the same type of error- choosing one of the widgets types is necessary for a successful widget configuration.

Thank you for your review, it will be taken into consideration 👍

**Comment by inbalzukerman** [comment]
Thank you for your review, the bug you described has been fixed 👍
