### ISSUE TITLE
General Information

### ISSUE THREAD

**Issue by EliaTraore** [TechnionYP5777/Smartcity-Smarthouse#241]
- Thanks to your help, we've found out that the dashboard widget is not user safe. This might result in crashs when trying to add widgets with incomplete information. Please try not to open duplicate bugs on that issue
- The bug in #234 have been fixed, we will update the release but the current workaround is to clone the source and work with it

Generally, please try to check this issue for future updates

**Comment by ylevv** [comment]
There is no general concept of a "user" in our system. The system is per house and closing the Smart-House won't save all the information you added, e.g. widgets. We do save your user details and emergency contacts (currently locally).

**Comment by RonGatenio** [comment]
Sorry about the misunderstandings yesterday... We think our wiki was a bit messy.
We have updated most of it. 

Can start again by reading the README, the wiki's [home](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki) or from the new [quick start section](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki#quick-start)

**Comment by ylevv** [comment]
Note: you don't have to register in order to get all the available functionality of the Smart-House (apart from adding emergency contacts).

**Comment by RonGatenio** [comment]
PLEASE CHECK OUT OUR [**NEW RELEASE**](https://github.com/TechnionYP5777/Smartcity-Smarthouse/releases/latest)

**Comment by inbalzukerman** [comment]
This issue was relevant to the final reviews, it can be closed now 😄
