### ISSUE TITLE
Undefined Room

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#242]
there is always undefined sensor showing...
![image](https://user-images.githubusercontent.com/23057199/27769196-60c4f204-5f2d-11e7-9859-e939b318c1fd.png)

**Comment by roy-shchory** [comment]
its not sensors its a mapping of the house, there is always an undefined room for sensors not binded to a specific room. please take a look at the wikis for more in depth explanations.

**Comment by DavidCohen55** [comment]
Where can I find this wiki page? I didn't understand why you need an undefined room for this...

**Comment by roy-shchory** [comment]
the mapping is more for the user to have a visual mapping of the sensors and there location.
if a sensor dosen't  have a fixed location - for example the vitals sensor which you wear and move with you you can place them in the UNDEFINED room.
there is no further use of the sensors location, only for this visualization.

**Comment by DavidCohen55** [comment]
Also I've just notice that there is a typo, its written UNDIFINED instead of **Undefined**

**Comment by roy-shchory** [comment]
we also noticed it thanks for the input! will be fixed in next release
