### ISSUE TITLE
Installation bug

### ISSUE THREAD

**Issue by kobybs** [TechnionYP5777/Smartcity-Smarthouse#244]
![image](https://user-images.githubusercontent.com/22766102/27769219-010ea124-5f2e-11e7-8023-4576a2b7a309.png)

**Comment by RonGatenio** [comment]
I think your jdk is not up-to-date

**Comment by kobybs** [comment]
![image](https://user-images.githubusercontent.com/22766102/27769229-37bfec1e-5f2e-11e7-9026-efb57271a66b.png)
when tried to double click

**Comment by RonGatenio** [comment]
The missing class is from JavaFX that comes with the JDK

**Comment by kobybs** [comment]
![image](https://user-images.githubusercontent.com/22766102/27769258-d3ce3868-5f2e-11e7-9579-e38d83325a50.png)

**Comment by RonGatenio** [comment]
Follow the instructions from [here](https://github.com/TechnionYP5777/Smartcity-Smarthouse#linux)

**Comment by ylevv** [comment]
Working in Linux perhaps? Look in our README, it contains the commands you need :)

**Comment by kobybs** [comment]
the sudo apt-get install openjfx fixed this. thanks.
