### ISSUE TITLE
Can't login

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#245]
there is only registration for the app but I can't use old details
Due to change version of the jar, my details were deleted and I should resubmit my details

**Comment by RonGatenio** [comment]
Which JARs did you try to run?
They are not linked, the Runnable.Apps don't save persistent data (they are for testing)
Only `System-1.01-jar-with-dependencies.jar` and `ApplicationsIncludedHouse-1.01-jar-with-dependencies.jar` save data

**Comment by DavidCohen55** [comment]
I've tried to work at first with System-1.01-jar-with-dependencies.jar and then I moved to ApplicationsIncludedHouse-1.01-jar-with-dependencies.jar ,is there a reason you can't login to the system and see details?

**Comment by RonGatenio** [comment]
Can you please send us the log reports (can be found in the Logs folder that was created in the same directory as the JAR)

**Comment by DavidCohen55** [comment]
I think that there is a misunderstanding, I mean that I need to register twice and maybe it is shown at your database that I have 2 contacts, but maybe you could have aloud login the system and get all of the emergency contacts and so on...

**Comment by ylevv** [comment]
Please see #241
