### ISSUE TITLE
gui alignment

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Smartcity-Smarthouse#246]
The sensor's name gets out of the room "box"

![image](https://user-images.githubusercontent.com/22842727/27769211-d9f8713c-5f2d-11e7-9844-198b1aea6d4b.png)

**Comment by DavidCohen55** [comment]
I've encountered it too...
![image](https://user-images.githubusercontent.com/23057199/27769230-39f1b1fc-5f2e-11e7-9ecd-d0545713b57a.png)

**Comment by roy-shchory** [comment]
working on it :)

**Comment by roy-shchory** [comment]
will be fixed in next release
