### ISSUE TITLE
Where do I get applications JAR files?

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/Smartcity-Smarthouse#249]
Hi,
In the manual I see I can add applications using JAR files, where do I get them?
Thanks

**Comment by RonGatenio** [comment]
From the zip folder: `Installable.Apps.zip` from the [release](https://github.com/TechnionYP5777/Smartcity-Smarthouse/releases/tag/v1.01)

**Comment by TomPalny** [comment]
Is this mentioned anywhere in the User Manual V2.0 ? perhaps I missed it

**Comment by RonGatenio** [comment]
These are just some example applications we have created. The real user should know about them, there for it is not in the manual.
