### ISSUE TITLE
Dashboard widget "Percentage"

### ISSUE THREAD

**Issue by TomPalny** [TechnionYP5777/Smartcity-Smarthouse#250]
Hi,
After I go to dashboard and select the first widget, "Percentage", I add it, and intentionally I do not add a path. I press OK and get a Null Pointer Exception.
This is unexpected behavior. It should not give me the option to add a widget if an actual path is necessary, or if you prefer to allow this and receive an error message, that message should contain the reason for the error. (I'm guessing it is because it can't find the widget)
Once I click the "try to recover" there's no recovery possible. 
Also, if I click "close" on the error message, it closes the whole system.

On the other hand, if I add widget "List Widget" I can add it without a path, click OK and no error shows.

**Comment by RonGatenio** [comment]
You are right, this bug will be fixed

**Comment by inbalzukerman** [comment]
Thank you for your review, the bug you described has been fixed 👍
