### ISSUE TITLE
User details validate

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#252]
It seems that there isn't checking for the user details in the: id and phone fields
phone should start with 05 and be 10 digits length, and id should be 9 digits

![image](https://user-images.githubusercontent.com/23057199/27787576-e3cca726-5fed-11e7-8fe5-900f7ed5aadf.png)

**Comment by EliaTraore** [comment]
You're right, but at the moment all the other functionalities are available even if the info is incorrect (except alerts that might be sent to wrong contacts, if you added problematic contact info).
Feel free to check those functionalities :smile:

**Comment by RonGatenio** [comment]
If you want to see the other things that you can do with the application you can view our new [Smarthouse Owner Manual](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/Smarthouse-Owner-Manual)

**Comment by inbalzukerman** [comment]
fixed the bug, thank you for your review 👍
