### ISSUE TITLE
Sensor simulator doesn't work

### ISSUE THREAD

**Issue by AnnaBel7** [TechnionYP5777/Smartcity-Smarthouse#253]
When I try to run `java -jar SensorsSimulator-1.01-jar-with-dependencies.jar` I get an error:
![image](https://user-images.githubusercontent.com/22842727/27788576-e36fd858-5ff1-11e7-8d20-6ec87031ac3f.png)

**Comment by RonGatenio** [comment]
I will fix it now. Thanks 😄

**Comment by RonGatenio** [comment]
Fixed it, it works now: [`SensorsSimulator-1.01-jar-with-dependencies.jar`](https://github.com/TechnionYP5777/Smartcity-Smarthouse/releases/download/v1.02/SensorsSimulator-1.01-jar-with-dependencies.jar)
