### ISSUE TITLE
Outmatching error for details 

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#254]
After I've installed the new release and tried to check the bug from issue #252 it seems that the error doesn't match the problem.

![image](https://user-images.githubusercontent.com/23057199/27788902-0434c142-5ff3-11e7-8e95-b47a47c94679.png)

**Comment by DavidCohen55** [comment]
Also there isn't support in phone length and 05
![image](https://user-images.githubusercontent.com/23057199/27789001-6aa3601e-5ff3-11e7-95fb-576656d4e436.png)

Also in ID there needs to be another message then "empty or only digits" 
![image](https://user-images.githubusercontent.com/23057199/27789037-87a2ebbc-5ff3-11e7-9f0b-48f9baf9203f.png)

**Comment by RonGatenio** [comment]
Thanks for the notification. We will fix it in our next release.

In the meantime, please check out other (and more relevant) aspects of our project. Read about them in the new [Smarthouse Owner Manual](https://github.com/TechnionYP5777/Smartcity-Smarthouse/wiki/Smarthouse-Owner-Manual).

Note that the user information page is not the center of our project, and we would love to get your feedback on the more relevant aspects of it.

**Comment by inbalzukerman** [comment]
fixed the bug, thank you for your review 👍
