### ISSUE TITLE
Room edit adds the same sensors

### ISSUE THREAD

**Issue by DavidCohen55** [TechnionYP5777/Smartcity-Smarthouse#256]
When I've tried to add a room with the same name it automatically added the room as the same as first including the sensors

![image](https://user-images.githubusercontent.com/23057199/27789473-7590715e-5ff5-11e7-999f-6fb77ab2705d.png)

**Comment by DavidCohen55** [comment]
And when I add a new sensor to one of them, you can see that every one adds it too... 
![image](https://user-images.githubusercontent.com/23057199/27789642-ffd42b6c-5ff5-11e7-80dc-4ed20a76970d.png)

**Comment by roy-shchory** [comment]
you are right i will fix it right now! duplicate  off #255

**Comment by DavidCohen55** [comment]
I've didn't saw the other issue... my bad...

**Comment by inbalzukerman** [comment]
Don't worry about it 😅
